services:
  hassio:
    container_name: ${HASSIO_CONTAINER_NAME}
    image: ${HASSIO_IMAGE_NAME}:${HASSIO_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${HASSIO_HTTP_PORT}:8123
    volumes:
      - default:/config
      - ${HASSIO_LOCAL_CONFIG}:/config/custom
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: ${HASSIO_CONTAINER_NAME}_network
    driver: bridge

volumes:
  default:
    name: ${HASSIO_CONTAINER_NAME}_data
    driver: local