version: '3.9'
services:
  web:
    image: homeassistant/home-assistant:latest
    container_name: hassio
    restart: always
    ports:
      - ${APP_PORT}:8123
    networks:
      - default
    volumes:
      - data:/config
      - ./data:/config

networks:
  default:
    name: docker_hassio_network
    driver: bridge

volumes:
  data:
    name: docker_hassio_data
    driver: local
